### ISSUE TITLE
Static-width gutters are not supported on small screens

### ISSUE THREAD

**Issue by jmikrut** [trouble/react-css-grid#1] opened 2019-11-02 18:35 UTC
This is what a `40px` column gap does to columns on small screens.

![image](https://user-images.githubusercontent.com/6651896/68075418-0306e180-fd7e-11e9-9fac-2dbd96cbce4e.png)

**Comment by jacobsfletch** [comment] 2019-11-07 22:08
@jmikrut This is because your statically defined gutter widths, multiplied by their quantity, is larger than the available horizontal real-estate -- so the CSS Grid Layout spec is shrinking them.

This is not a bug, but a symptom of a larger design problem, which is the need to support an alternate grid with a reduced `hCount` (aka, a mobile grid). This _will_ be addressed in later releases. Keeping this ticket open for accountability.

**Comment by jacobsfletch** [comment] 2022-05-13 00:43
Mobile grids are now supported, so in cases like this where gutters collapse, the solution is to use [breakpoints](https://www.faceless-ui.com/docs/css-grid/api#provider-props) to reduce the number of columns or gutter size based on screen size.

**Closed as completed by jacobsfletch** 2022-05-13 00:43 UTC
